#!/usr/bin/env bash
# loops from 1 to 10 and displays
#+ "bad luck" for the 4th loop iteration
#+ "good luck" for the 8th loop iteration
#+ "Best School" for the other iterations

c=1
while [ $c -le 10 ];
do
	if [ $c -eq 4 ]
    	then
	echo "bad luck"
	elif [ $c -eq 8 ]
	then 
	echo "good luck"
	else
	echo "Best School"
	fi
    (( c=c+1 ))
done